"use client";

import Head from 'next/head';
import Navbar from './navbar';
import Drawer from './drawer';
import Canvas from './canvas';
import AddText from './addtext';
import Chat from './chat';

import Script from 'next/script'

import { useSocket } from '../context/SocketProvider';
import { useEffect, useState } from 'react';

export default function Home() {
  const { sendDraw, sendMessage} = useSocket()
  const [message,setMessage]=useState('')
  useEffect(() => {
  
  }, [])
  return (
    <div>
      <Head>
        <title>Hidraw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <script src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>

      </Head>
      <div className='bg-black h-[900px] w-[1500px]'>
        <Navbar />
        <Drawer />
        <Canvas />
        <AddText />
        <Chat/>
      </div>
      <Script src="/scripts/index.js" />
    </div>
  );
}
